apiVersion: arcdata.microsoft.com/v3
kind: DataController
metadata:
  annotations:
    management.azure.com/apiVersion: "2021-11-01"
    management.azure.com/correlationId: 77b58d7d-f387-4226-9120-a0767fccee1c
    management.azure.com/customLocation: /subscriptions/182c901a-129a-4f5d-86e4-cc6b294590a2/resourceGroups/raki-sql-to-miaa-migration-test-rg/providers/microsoft.extendedlocation/customlocations/arcdatacl
    management.azure.com/location: eastus
    management.azure.com/operationId: d70da673-c101-45f9-8538-deeac8254a19*E4EEAC1489BD641068AF579BAEFF7A43EF4AE29BB499D7C1258D527BF5A3B5C1
    management.azure.com/resourceId: /subscriptions/182c901a-129a-4f5d-86e4-cc6b294590a2/resourceGroups/raki-sql-to-miaa-migration-test-rg/providers/microsoft.azurearcdata/dataControllers/arc-dc
    management.azure.com/tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
    traceparent: 00-46c4005ae8220d41826a5f2f8fecb72e-a193c2316ff3dbfc-01
  creationTimestamp: "2022-03-01T01:41:34Z"
  generation: 1
  name: arc-dc
  namespace: arc
  resourceVersion: "741155"
  uid: 2c5c3b05-a0e4-414e-9b67-2c74bd3b97d1
spec:
  credentials:
    dockerRegistry: arc-private-registry
    domainServiceAccount: domain-service-account-secret
    serviceAccount: sa-arc-controller
  docker:
    imagePullPolicy: Always
    imageTag: v1.4.0_2022-02-25
    registry: mcr.microsoft.com
    repository: arcdata
  infrastructure: azure
  security:
    allowDumps: true
    allowNodeMetricsCollection: true
    allowPodMetricsCollection: true
  services:
  - name: controller
    port: 30080
    serviceType: LoadBalancer
  settings:
    ElasticSearch:
      vm.max_map_count: "-1"
    azure:
      autoUploadLogs: "true"
      autoUploadMetrics: "true"
      connectionMode: direct
      location: eastus
      resourceGroup: raki-sql-to-miaa-migration-test-rg
      subscription: 182c901a-129a-4f5d-86e4-cc6b294590a2
    controller:
      displayName: arc-dc
      logs.rotation.days: "7"
      logs.rotation.size: "5000"
  storage:
    data:
      accessMode: ReadWriteOnce
      className: default
      size: 15Gi
    logs:
      accessMode: ReadWriteOnce
      className: default
      size: 10Gi
status:
  azure:
    uploadStatus:
      logs:
        lastUploadTime: "0001-01-01T00:00:00.000000Z"
        message: ""
      metrics:
        lastUploadTime: "2022-03-01T01:58:00.813754Z"
        message: No Azure resource to upload.
      usage:
        lastUploadTime: "2022-03-01T01:44:02.484442Z"
        message: No usage to upload. The number of Azure resources is 0
  lastUpdateTime: "2022-03-01T02:00:00.829683Z"
  observedGeneration: 1
  runningVersion: v1.4.0_2022-02-25
  state: Ready
